name = "demo-cloudflare-shopify"
main = "src/GetCustomer.js"
compatibility_date = "2023-04-18"

workers_dev = true

rules = [
  { type = "Data", globs = ["**/*.suma.js", "**/*.supr", "**/*.provider.json"], fallthrough = true }
]
